name: revealjs
description: A dart wrapper to the reveal.js library
version: 0.0.1
homepage: https://github.com/jackd/revealjs-dart
author: Dominic Jack <thedomjack@gmail.com>

environment:
  # sdk: '>=2.0.0-dev.68.0 <3.0.0'
  sdk: '^2.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  # test: ^1.3.0
  build_runner: ^0.9.1+1
  build_web_compilers: ^0.4.0+4
  # build_test: ^0.10.2
